server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8080/realms/oauth2
          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
#          jws-algorithms: RS256
#          audiences: http://localhost:8082  # ??? ??
#          public-key-location: classpath:certs/publicKey.txt    # OAuth2 2.0 JWS ??? ?? PublicKey ?? ??

#          jws-algorithms: HS256
#          jws-algorithms: RS512
#          public-key-location: classpath:certs/publicKey.txt